POKEMON["Turtwig"] = {
    pTypes = { ELEMENT_GRASS },
    dexStorage = 10387,
    atk = 68,
    def = 64,
    spAtk = 45,
    spDef = 55,
    energy = 100,
    chance = 150,
    portrait = 30136,
    dexPortrait = 30136,
    fastcallPortrait = 28779,
    catchStorage = 16387,
    evolutions = { { name = "Grotle", requiredLevel = 35 } },
    description = "The shell on its back is made of soil. On a very healthy TURTWIG, the shell should feel moist.",
    skills = { "Tackle", 1, "Headbutt", 5, "Absorb", 9, "Razor Leaf", 13, "Curse", 17, "Bite", 21, "Mega Drain", 25,  "Leech Seed", 29, "Synthesis", 33, "Crunch", 37, "Giga Drain", 41, "Leaf Storm", 45 },
    abilities = { POKEMON_ABILITIES.STRENGTH, POKEMON_ABILITIES.SHELL_ARMOR, "Headbutt" },
	eggGroup = { POKEMON_EGG_GROUP_MONSTER, POKEMON_EGG_GROUP_GRASS },
    eggId = 13978,
    eggChance = 20,
    specialAbilities = { POKEMON_SPECIAL_ABILITY_IDS.OVERGROW },
    learnableTms = { TM_IDS.SOFTBOILED, TM_IDS.ENERGY_BALL, TM_IDS.FURY_CUTTER, TM_IDS.DEFENSE_CURL, TM_IDS.SLUDGE_BOMB, TM_IDS.MUD_SLAP, TM_IDS.GIGA_DRAIN, TM_IDS.HEADBUTT, TM_IDS.SWORDS_DANCE, TM_IDS.TOXIC, TM_IDS.BODY_SLAM, TM_IDS.TAKE_DOWN, TM_IDS.DOUBLE_EDGE, TM_IDS.RAGE, TM_IDS.MEGA_DRAIN, TM_IDS.SOLAR_BEAM, TM_IDS.MIMIC, TM_IDS.DOUBLE_TEAM, TM_IDS.REFLECT, TM_IDS.BIDE, TM_IDS.REST, TM_IDS.SUBSTITUTE, TM_IDS.BULLET_SEED, TM_IDS.LIGHT_SCREEN, TM_IDS.SAFEGUARD },
    eggMoves = { "Amnesia", "Charm", "Curse", "Endure", "Giga Drain", "Grass Whistle", "Grassy Terrain", "Ingrain", "Leaf Storm", "Magical Leaf", "Nature Power", "Petal Dance", "Power Whip", "Skull Bash", "Sludge" }
}